apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
  labels:
    app.kubernetes.io/chain-node: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
    app.kubernetes.io/chain-name: {{ .Values.config.chainName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/chain-node: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
  template:
    metadata:
      labels:
        app.kubernetes.io/chain-node: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
        app.kubernetes.io/chain-name: {{ .Values.config.chainName }}
    spec:
      shareProcessNamespace: true
      containers:
      {{- if .Values.debug.enabled }}
      - image: {{ printf "%s:%s" .Values.debug.imageName .Values.debug.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: debug
        ports:
          - containerPort: 9999
            protocol: TCP
            name: debug
        env:
          - name: HTTP_PORT
            value: '9999'
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      {{- end }}
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.network.imageName }}:{{ .Values.network.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: network
        ports:
          - containerPort: 40000
            protocol: TCP
            name: network
          - containerPort: 50000
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - network run
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.consensus.imageName }}:{{ .Values.consensus.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: consensus
        ports:
          - containerPort: 50001
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          {{- if eq .Values.consensus.imageName "consensus_raft" }}
          - consensus run --stdout
          {{- else }}
          - consensus run
          {{- end }}
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      {{- if contains "chaincode" .Values.executor.imageName }}
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.executor.imageName }}:{{ .Values.executor.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: executor
        ports:
          - containerPort: 50002
            protocol: TCP
            name: grpc
          - containerPort: 7052
            protocol: TCP
            name: chaincode
          - containerPort: 7053
            protocol: TCP
            name: eventhub
        command:
          - sh
          - -c
          - executor run -p 50002 --couchdb-username citacloud --couchdb-password citacloud
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      - image: {{ printf "%s:%s" .Values.stateDB.imageName .Values.stateDB.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: stateDB
        ports:
          - containerPort: 5984
            protocol: TCP
            name: couchdb
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v/state-data" .Values.config.chainName .Values.config.domain }}
            mountPath: /opt/couchdb/data
        env:
          - name: COUCHDB_USER
            value: citacloud
          - name: COUCHDB_PASSWORD
            value: citacloud
      {{- else }}
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.executor.imageName }}:{{ .Values.executor.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: executor
        ports:
          - containerPort: 50002
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - executor run
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      {{- end }}
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.storage.imageName }}:{{ .Values.storage.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: storage
        ports:
          - containerPort: 50003
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - storage run
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.controller.imageName }}:{{ .Values.controller.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: controller
        ports:
          - containerPort: 50004
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - controller run -p 50004
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      - image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.kms.imageName }}:{{ .Values.kms.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: kms
        ports:
          - containerPort: 50005
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - kms run
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
            mountPath: /data
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName | quote }}
