apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
  labels:
    node_name: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
    chain_name: {{ .Values.config.chainName }}
spec:
  ports:
    - port: 40000
      targetPort: 40000
      protocol: TCP
      name: network
    - port: 50004
      targetPort: 50004
      protocol: TCP
      name: rpc
    - port: 50002
      targetPort: 50002
      protocol: TCP
      name: call
  selector:
    node_name: {{ printf "%s-%v" .Values.config.chainName .Values.config.domain }}
