# Default values for cita-cloud-local-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# pvcName -- Name of persistentVolumeClaim.
pvcName: "local-pvc"

image:
  # image.pullPolicy -- pullPolicy for cita_cloud_config docker images.
  pullPolicy: Always

config:
  # config.imageTag -- Image tag of cita-cloud-config container.
  imageTag: v6.5.0
  # config.chainName -- Chain name of cita-cloud blockchain that will be changed.
  chainName: test-chain

  action:
    # config.action.type -- Action of cita-cloud-config. If the chain's nodes are in a k8s cluster, you should use xxxSingle action; if the chain's nodes are in multi k8s clusters, you should use xxxMulti action; the clean action is universal.
    type: increaseSingle
