{{ $releaseName := .Release.Name }}
{{ $namespace := .Release.Namespace }}
{{- range int .Values.replicaCount | until }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ . }}
  namespace: {{ $namespace }}
spec:
  type: NodePort
  ports:
    - name: network
      port: 40000
      protocol: UDP
      targetPort: 40000
    - port: 50004
      targetPort: 50004
      protocol: TCP
      name: rpc
    - port: 50002
      targetPort: 50002
      protocol: TCP
      name: call
  selector:
    statefulset.kubernetes.io/pod-name: {{ $releaseName }}-{{ . }}
    {{- end }}