apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-node-port" .Release.Name }}
  labels:
    {{- include "cita-cloud-local-cluster.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 50004
      targetPort: 50004
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: rpc
    - port: 50002
      targetPort: 50002
      nodePort: {{ .Values.service.vmPort }}
      protocol: TCP
      name: call
  selector:
    {{- include "cita-cloud-local-cluster.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
