apiVersion: batch/v1
kind: Job
metadata:
  name: cita-cloud-config
spec:
  template:
    spec:
      containers:
      - name: cloud-config
        image: {{ printf "citacloud/cloud-config:%s" .Values.config.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - "/data/action.sh"
        args:
          # chainName
          - -c
          - {{ .Values.config.chainName | quote }}
          # action.type
          - -t
          - {{ .Values.config.action.type | quote }}
        volumeMounts:
        - name: datadir
          mountPath: /data
        - name: cloud-config-job-shell
          mountPath: /data/action.sh
          subPath: action.sh
      volumes:
      - name: cloud-config-job-shell
        configMap:
          name: cloud-config-job-shell
          defaultMode: 0744
      - name: datadir
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName | quote }}
      restartPolicy: Never
  backoffLimit: 1