apiVersion: batch/v1
kind: Job
metadata:
  name: cita-cloud-config
spec:
  template:
    spec:
      containers:
      - name: cloud-config
        image: {{ printf "citacloud/cloud-config:%s" .Values.config.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - "/data/action.sh"
        args:
          # chainName
          - -c
          - {{ .Values.config.chainName | quote }}
          # action.type
          - -t
          - {{ .Values.config.action.type | quote }}
          # increaseSingle.kmsPassword
          - -p
          - {{ .Values.config.action.increaseSingle.kmsPassword | quote }}
          # initMulti.superAdmin
          - -s
          - {{ .Values.config.action.initMulti.superAdmin | quote }}
          # initMulti.kmsPasswordList
          - -P
          - {{ .Values.config.action.initMulti.kmsPasswordList | quote }}
          # initMulti.nodeList
          - -N
          - {{ .Values.config.action.initMulti.nodeList | quote }}
          # initMulti.blockInterval
          - -i
          - {{ .Values.config.action.initMulti.blockInterval | quote }}
          # initMulti.blockLimit
          - -l
          - {{ .Values.config.action.initMulti.blockLimit | quote }}
          # initMulti.logLevel
          - -L
          - {{ .Values.config.action.initMulti.logLevel | quote }}
          # initMulti.networkImage
          - -x
          - {{ .Values.config.action.initMulti.networkImage | quote }}
          # initMulti.consensusImage
          - -y
          - {{ .Values.config.action.initMulti.consensusImage | quote }}
          # initMulti.kmsImage
          - -z
          - {{ .Values.config.action.initMulti.kmsImage | quote }}
          # increaseMulti.kmsPassword
          - -Q
          - {{ .Values.config.action.increaseMulti.kmsPassword | quote }}
          # increaseMulti.node
          - -n
          - {{ .Values.config.action.increaseMulti.node | quote }}
          # decreaseMulti.domain
          - -d
          - {{ .Values.config.action.decreaseMulti.domain | quote }}
        volumeMounts:
        - name: datadir
          mountPath: /data
        - name: cloud-config-job-shell
          mountPath: /data/action.sh
          subPath: action.sh
      volumes:
      - name: cloud-config-job-shell
        configMap:
          name: cloud-config-job-shell
          defaultMode: 0744
      - name: datadir
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName | quote }}
      restartPolicy: Never
  backoffLimit: 1