kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.scName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.size }}
