# Default values for cita-cloud-local-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # global.registry -- You can specify the image registry.
  registry: docker.io
  # global.repository -- You can specify the image repository.
  repository: citacloud

# replicaCount -- Count of blockchain nodes.
replicaCount: 4

# pvcName -- Name of persistentVolumeClaim.
pvcName: "local-pvc"

config:
  # config.superAdmin -- Super admin account address.
  superAdmin: 8f81961f263f45f88230375623394c9301c033e7
  # config.imageName -- docker image  of cloud-config.
  imageName: cloud-config
  # config.imageTag -- Image tag of cloud-config container.
  imageTag: v6.6.1
  # config.blockInterval -- Chain's block interval.
  blockInterval: 3
  # config.blockLimit --Chain's block limit.
  blockLimit: 100
  # config.logLevel -- Log level warn/info/debug/trace
  logLevel: info

image:
  # image.pullPolicy -- pullPolicy for all docker images.
  pullPolicy: Always

debug:
  # debug.enabled -- Is there a debug container in each pod?
  enabled: false
  # debug.imageName -- Image name of debug container.
  imageName: praqma/network-multitool
  # debug.imageTag -- Image tag of debug container.
  imageTag: latest

network:
  # network.imageName -- docker image of network container.
  imageName: network_zenoh
  # network.imageTag -- Image tag of network container.
  imageTag: v6.6.1

consensus:
  # consensus.imageName -- docker image of consensus container. consensus_raft or consensus_bft or consensus_overlord
  imageName: consensus_bft
  # consensus.imageTag -- Image tag of consensus container.
  imageTag: v6.6.1

executor:
  # executor.imageName -- docker image of executor container. executor_evm or executor_poc or executor_chaincode_ext
  imageName: executor_evm
  # executor.imageTag -- Image tag of executor container.
  imageTag: v6.6.1

stateDB:
  # stateDB.imageName -- docker image of stateDB container.
  imageName: couchdb
  # stateDB.imageTag -- Image tag of stateDB container.
  imageTag: latest

storage:
  # storage.imageName -- docker image of storage container. storage_rocksdb or storage_sqlite
  imageName: storage_rocksdb
  # storage.imageTag -- Image tag of storage container.
  imageTag: v6.6.1

controller:
  # controller.imageName -- docker image of controller container.
  imageName: controller
  # controller.imageTag -- Image tag of controller container.
  imageTag: v6.6.1

crypto:
  # crypto.imageName -- docker image of crypto container. crypto_sm or crypto_eth
  imageName: crypto_sm
  # crypto.imageTag -- Image tag of crypto container.
  imageTag: v6.6.1

# The following are just some reference values, you must set the following values according to the actual environment
resources:
  requests:
    # resources.requests.cpu -- cpu request
    cpu: 10m
    # resources.requests.memory -- memory request
    memory: 32Mi
  limits:
    # resources.limits.cpu -- cpu limit
    cpu: 4000m
    # resources.limits.memory -- memory limit
    memory: 8192Mi

exporter:
  # exporter.enabled -- Is there an exporter container in each pod?
  enabled: false
  # exporter.imageName -- Image name of exporter container.
  imageName: monitor-citacloud-exporter
  # exporter.imageTag -- Image tag of exporter container.
  imageTag: latest