# Default values for cita-cloud-multi-cluster-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  registry: docker.io
  repository: citacloud

# pvcName -- Name of persistentVolumeClaim.
pvcName: local-pvc

config:
  # config.chainName -- Chain name of cita-cloud blockchain that will be setup.
  chainName: test-chain
  # config.domain -- Domain of the node that will be setup.
  domain: node0

image:
  # image.pullPolicy -- pullPolicy for all docker images IfNotPresent/Always.
  pullPolicy: Always

debug:
  # debug.enabled -- Is there a debug container in each pod?
  enabled: true
  # debug.imageName -- Image name of debug container.
  imageName: praqma/network-multitool
  # debug.imageTag -- Image tag of debug container.
  imageTag: latest

network:
  # network.imageName -- docker image of network container. network_p2p or network_tls
  imageName: network_tls
  # network.imageTag -- Image tag of network container.
  imageTag: latest

consensus:
  # consensus.imageName -- docker image of consensus container. consensus_raft or consensus_bft
  imageName: consensus_bft
  # consensus.imageTag -- Image tag of consensus container.
  imageTag: latest

executor:
  # executor.imageName -- docker image of executor container. executor_evm or executor_poc or executor_chaincode_ext
  imageName: executor_evm
  # executor.imageTag -- Image tag of executor container.
  imageTag: latest

stateDB:
  # stateDB.imageName -- docker image of stateDB container.
  imageName: couchdb
  # stateDB.imageTag -- Image tag of stateDB container.
  imageTag: latest

storage:
  # storage.imageName -- docker image of storage container. storage_rocksdb or storage_sqlite
  imageName: storage_rocksdb
  # storage.imageTag -- Image tag of storage container.
  imageTag: latest

controller:
  # controller.imageName -- docker image of controller container.
  imageName: controller
  # controller.imageTag -- Image tag of controller container.
  imageTag: latest

kms:
  # kms.imageName -- docker image of kms container. kms_sm or kms_eth
  imageName: kms_sm
  # kms.imageTag -- Image tag of kms container.
  imageTag: latest

# The following are just some reference values, you must set the following values according to the actual environment
resources:
  requests:
    # resources.requests.cpu -- cpu request
    cpu: 10m
    # resources.requests.memory -- memory request
    memory: 32Mi
  limits:
    # resources.limits.cpu -- cpu limit
    cpu: 4000m
    # resources.limits.memory -- memory limit
    memory: 8192Mi
