apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
  labels:
    node_name: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
    chain_name: {{ .Values.config.chainName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      node_name: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
  template:
    metadata:
      labels:
        node_name: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
        chain_name: {{ .Values.config.chainName }}
    spec:
      shareProcessNamespace: true
      containers:
      {{- if .Values.debug.enabled }}
      - image: {{ printf "%s:%s" .Values.debug.imageName .Values.debug.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: debug
        ports:
          - containerPort: 9999
            protocol: TCP
            name: debug
        env:
          - name: HTTP_PORT
            value: '9999'
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      {{- end }}
      - image: {{ printf "%s:%s" .Values.network.imageName .Values.network.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: network
        ports:
          - containerPort: 40000
            protocol: TCP
            name: network
          - containerPort: 50000
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - network run -p 50000 -k network_key
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      - image: {{ printf "%s:%s" .Values.consensus.imageName .Values.consensus.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: consensus
        ports:
          - containerPort: 50001
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - consensus run -p 50001
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      {{- if contains "chaincode" .Values.executor.imageName }}
      - image: {{ printf "%s:%s" .Values.executor.imageName .Values.executor.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: executor
        ports:
          - containerPort: 50002
            protocol: TCP
            name: grpc
          - containerPort: 7052
            protocol: TCP
            name: chaincode
          - containerPort: 7053
            protocol: TCP
            name: eventhub
        command:
          - sh
          - -c
          - executor run -p 50002 --couchdb-username citacloud --couchdb-password citacloud
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      - image: {{ printf "%s:%s" .Values.stateDB.imageName .Values.stateDB.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: stateDB
        ports:
          - containerPort: 5984
            protocol: TCP
            name: couchdb
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v/state-data" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /opt/couchdb/data
        env:
          - name: COUCHDB_USER
            value: citacloud
          - name: COUCHDB_PASSWORD
            value: citacloud
      {{- else }}
      - image: {{ printf "%s:%s" .Values.executor.imageName .Values.executor.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: executor
        ports:
          - containerPort: 50002
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - executor run -p 50002
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      {{- end }}
      - image: {{ printf "%s:%s" .Values.storage.imageName .Values.storage.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: storage
        ports:
          - containerPort: 50003
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - storage run -p 50003
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      - image: {{ printf "%s:%s" .Values.controller.imageName .Values.controller.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: controller
        ports:
          - containerPort: 50004
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - controller run -p 50004
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
      - image: {{ printf "%s:%s" .Values.kms.imageName .Values.kms.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: kms
        ports:
          - containerPort: 50005
            protocol: TCP
            name: grpc
        command:
          - sh
          - -c
          - kms run -p 50005 -k /kms/key_file
        workingDir: /data
        volumeMounts:
          - name: datadir
            subPathExpr: {{ printf "%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
            mountPath: /data
          - name: kms-key
            mountPath: /kms
            readOnly: true
      volumes:
        - name: kms-key
          secret:
            secretName: {{ printf "kms-secret-%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName | quote }}
